server:
  port: 9909
  servlet:
    context-path: /talimat

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL:jdbc:oracle:thin:@10.120.201.21:1521:fnsdevdb}
    username: ${DB_USERNAME:PTT}
    password: ${DB_PASSWORD:ptt_2005*}
    hikari:
      maximum-pool-size: 150
      max-lifetime: 3600000
      idle-timeout: 3600000
      connection-timeout: 3600000
      validation-timeout: 3600000
      minimum-idle: 25
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 10000
        order_inserts: true
        order_updates: true
        generate_statistics: false
      javax:
        persistence:
          validation:
            mode: none

kurum:
  active: TEST


tandem:
  address: ${ADDRESS:http:\\10.120.200.161:30000/tandem-client}
